### ISSUE TITLE
ActiveHTMLWidget: fails with AttributeError: object has not attribute 'name'

### ISSUE THREAD

**Issue by ivarzap** [ioam/paramnb#73]
From the holoviews/examples/user_guide/15-Dashboards.ipynb, 
the last cell fails when executed as:
![image](https://user-images.githubusercontent.com/25571178/31279614-eeb0dcfa-aaa9-11e7-9e48-396529739ffa.png)

**Comment by PeterDSteinberg** [comment]
Hi @ceball @philippjfr @jbednar I spent the weekend getting better acquainted with `holoviews` , `paramnb`, and `bokeh` widgets as part of getting ready for AGU (December) and making some screenshots for a proposal.  I'm blocked by this issue without workaround (as far as I can tell) when trying to do interactive examples mentioned in [the Additional Features docs](http://nbviewer.jupyter.org/urls/notebooks.anaconda.org/cball/ioam-paramnb-additionalfeatures/download?version=) and similar.  Is anyone working on a fix?  Should I assign myself to this one?

**Comment by philippjfr** [comment]
You can fix it by downgrading to ipywidgets 6.x for the time being. I don't think an actual fix should be hard, it may just be a matter of readding a name variable to the widget.

That said the future of paramnb is somewhat up in the air because we'd like to focus on parambokeh in future. Definitely still worth fixing though, so if you have the time to investigate that would be very much appreciated.

**Comment by PeterDSteinberg** [comment]
Great context info - thanks, @philippjfr .  As far as my current work with these viz tools, which relates primarily to client demos, should I start moving towards `parambokeh`?  I'll give `parambokeh` a try today, as well as the downgrading workaround you mentioned for `paramnb`.

**Comment by philippjfr** [comment]
We haven't actually released a version of parambokeh that works with bokeh 0.12.10, which is what we recommend everyone should use. You can get a version that does work from @ceball's channel though, using

``conda install -c cball parambokeh``
